sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js: '8'
install: npm install
before_script:
  - npx cypress verify &
  - cd stories
  - npm install
  - cd ..
script:
  - kcd-scripts validate lint,build-and-test,test:cover,test:ts
  - kcd-scripts validate test:flow:coverage,test:ssr,test:cypress
after_success: kcd-scripts travis-after-success
branches:
  only: master
